
- name: Install Packages
  apt:
    name:
    - python3-pip
    - curl
    - wget
    - gnupg2
    - python3-git
    state: present
  
- name: Add Zeek apt repo key
  apt_key:
    url: https://download.opensuse.org/repositories/security:zeek/xUbuntu_22.04/Release.key

- name: Add Zeek apt repo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /
    state: present

- name: Install Zeek
  apt:
    name: zeek
    state: present

- name: Install Zeek package manager
  pip:
    name: zkg
    state: present
    executable: pip3

- name: Copy node.cfg file
  template:
    src: node.cfg
    dest: /opt/zeek/etc/node.cfg
    owner: root
    group: zeek
    mode: 0640

- name: Deploy Zeek
  command: /opt/zeek/bin/zeekctl deploy

- name: Add zeek executable to PATH.
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:/opt/zeek/bin'
    mode: "0644"
